### ISSUE TITLE
Request: Method to directly select a mode

### ISSUE THREAD

**Issue by RvonMallesch** [sidoh/esp8266_milight_hub#147]
Hi again,

I believe it would be a great feature to have method to choose the disco mode directly. As you would know, to do this in the UDP command, the first command after the remote style is 0x06 and the following command repeated 4 times is the mode number.

Many thanks for your fantastic work on this project!

Richard

**Comment by sidoh** [comment]
Which bulb type are you wanting to do this for?  It's only not possible with RGB, and this is because my understanding of the protocol has led me to believe it's not possible.

You should see this in the UI for RGBW, RGB+CCT, and FUT089:

![image](https://user-images.githubusercontent.com/589893/32358889-bf36af14-c006-11e7-9600-3c6699c71147.png)

It's possible to set the mode directly for these bulb types in the REST API or MQTT integration by supplying, for example, `{"mode":5}` in the request body or message payload.

Is this not what you mean?

**Comment by RvonMallesch** [comment]
DOH! Please ignore me, I simply failed to see it in the list of commands available.

Apologies for wasting your time on this,

Richard

**Comment by sidoh** [comment]
No worries -- the documentation isn't exactly perfectly organized either.  Glad you found what you're looking for :)
