### ISSUE TITLE
next_mode and previous_mode should update based on known state

### ISSUE THREAD

**Issue by servim** [sidoh/esp8266_milight_hub#169]
Hello! I'm not sure I can explain, my English is quite bad.
I have a light bulb RGBW, firmware 1.6.0
Command: next_mode it works, the mode changes from 0 to 8. But if the mode is changed through the mode: {"state":"ON","mode":"0"}, then this command will continue from the place where it finished, and not from the last mode. Eg:
![1](https://user-images.githubusercontent.com/22333446/33227099-e2a18ea6-d1d6-11e7-8f87-8a3febeb5219.png)

Command: previous_mode, changes mode 15,2,1,0,15,2,1,0 etc
![2](https://user-images.githubusercontent.com/22333446/33227105-f5c41efe-d1d6-11e7-9c28-2a5b46379ff3.png)

Is this expected behavior?

**Comment by sidoh** [comment]
Ah, yes.  This is not how it should work, but I see why it's doing this.  Should be able to fix this in a future version.  Thanks for reporting.

**Comment by servim** [comment]
the question is not the topic:
Command: mode_speed_up and mode_speed_down, works, but it is not clear, the current state, what is the range from the minimum to the maximum? mosquito does not return status.

**Comment by sidoh** [comment]
There isn't a way to directly set speed.  It can only be controlled with increase/decrease commands.  Because of this it's tricky to know what speed the bulb is at.  espMH doesn't currently track speed, but I believe the range is [0, 10].

It's possible to know what the state is by, for example, sending the maximum number of decrease commands.  Then you know the device is at speed 0.

**Comment by servim** [comment]
Thank you! I thought so :(

**Comment by sidoh** [comment]
was added in 1.7
