### ISSUE TITLE
MQTT: how to send raw RF packet and CCT globe to full brightness?

### ISSUE THREAD

**Issue by Skinah** [sidoh/esp8266_milight_hub#213]
Is there any way via MQTT to send raw RF packets? The wiki states it can be done via REST api, so can it be done via MQTT? if so how?

Same question for sending the command to go directly to full brightness for CCT globes.

I have almost finished writing an Openhab2 binding for this EspMilightHub and am hoping I can improve the way the CCT globes are handled before releasing the binding.

**Comment by sidoh** [comment]
Yup, it's possible.  Any command you can send to the REST API you can send to the corresponding MQTT topic.

Is there a command to set CCT globes to full brightness?  There's some related discussion [here](https://github.com/sidoh/esp8266_milight_hub/issues/170#issuecomment-354954595).  I'm not aware of any such command, which is why the CCT brightness handling is as janky as it is.
