### ISSUE TITLE
FUT089 saturation changes color_temp in white mode via control panel controls

### ISSUE THREAD

**Issue by Skinah** [sidoh/esp8266_milight_hub#255]
If you use the controls in the hubs control panel, the ones found using the IP address in a browser the saturation control will send MQTT states that have the color_temp change as you move the saturation control. Controls work fine in color mode, this is only when the globe is in white mode.

milight/states/0x99/fut089/7 {"state":"ON","color_temp":153,"bulb_mode":"white"}

**Comment by sidoh** [comment]
Try selecting a hue.  Color mode is only set when the hue is known.

**Comment by sidoh** [comment]
Oh, misunderstood.  But the reason is related.  The FUT089 protocol uses the same command ID for both color temp and saturation settings (no idea why).  So if the bulb mode is white, it'll send the right packet, but interpret it incorrectly later.

I suppose the options are:

1. Refuse to set saturation when bulb mode is not color (this seems unnecessarily confusing)
1. Force the bulb into color mode by setting a default hue (or last known hue) if one is not provided

**Comment by sidoh** [comment]
I think the automatic mode switching added in 1.7 kind of already accomplishes this.  It's a little confusing because it doesn't permanently switch into the relevant mode, but I think it at least solves the problem.
