### ISSUE TITLE
Listening for FUT091/B2 remote packets and sending FUT007 compatible ones.

### ISSUE THREAD

**Issue by jack1142** [sidoh/esp8266_milight_hub#316]
Hi,
Today I've got a new B2 remote and I though I could easily pair it with my FUT017s, but as it turned out, it doesn't seem to work, so now I'm thinking of alternate solution, which wouldn't require me to waste a lot of cash on new FUT091 remote and all new compatible bulbs.

It's not really an issue maybe, but I was wondering if it would be possible to use B2 remote with old milight bulbs (FUT017 in my case) which only supports old FUT007 controller. I was thinking of listening for packets sent by B2 remote and after getting them, sending the proper one for old bulbs. Problem is I have absolutely no idea, how to do it, as I'm waiting for ESP8266 for now and I can't really test anything. I was hoping for some tips, how I could achieve this.

I must say I'm really surprised that it doesn't work with FUT017 though, as everywhere I looked it's listed in supported ones for either FUT007 and also for FUT091, which uses the same protocol as B2.

Also I have Home Assistant set up, so maybe it would be just simple using trigger and sending another command back? I saw it has small latency, so seems like viable solution, if it's really that simple (it would probably be easier, if I have esp8266 already, but at least I can start thinking how to do it).

Thanks for any help.

**Comment by sidoh** [comment]
It's possible, but not directly with espMH.

You've got the right idea using HASS.  espMH can be configured to emit MQTT messages when it intercepts a Milight packet.  You could set up HASS (or some other MQTT-capable automation system) to listen for those MQTT messages, transform them, and send to the MQTT command topic which espMH is listening to.

Here's an example:

https://github.com/sidoh/esp8266_milight_hub/wiki/Using-Milight-Remote-with-HomeAssistant

Going to close the issue since it seems like it's already possible, but feel free to re-open if you have further questions.
