### ISSUE TITLE
Any working IOS App?

### ISSUE THREAD

**Issue by Mazdaracer121** [sidoh/esp8266_milight_hub#340]
In original Milight app i see just one of Virtual bridges...
any other does not appear

**Comment by sidoh** [comment]
I think this one works: https://play.google.com/store/apps/details?id=com.jaspergoes.bilight&hl=en_US

**Comment by Mazdaracer121** [comment]
Need an ios app. Not an android 😎

**Comment by sidoh** [comment]
haha.  sorry.

nope, not aware of anything other than the native android app.

this project is mainly meant to integrate with home automation platforms like HASS, openhab, etc.

going to close because i don't think i can help with this, but let me know if you have ideas.

**Comment by rhamblen** [comment]
Several ideas
I use SmartThings and can manage all the lights... colour and brightness.
But any of the home automation where they have the iOS app and integrate should work.

**Comment by david-strauss-privoro** [comment]
I know this issue is closed, but would there be any interest in working on an open sourced iOS project with me?

I've got a basic one going currently using AlamoFire and another library for a color picker, and I've got lots of ideas of where this app could go, such as including new modes and music modes, which I've also seen mentioned in other issues on this project.

Let me know!
