### ISSUE TITLE
Missing button presses / CCT remote and bulbs

### ISSUE THREAD

**Issue by jussbba** [sidoh/esp8266_milight_hub#360]
Hello,

My esp8266 milight hub is frequently missing buttons presses. It misses usually only one press (sometimes 2 or 3) and then when pressing button again it works. It feels like it is freezing. By freezing I mean that the esp8266 light does not blink 3 times when the button is pressed on the remote. The light is getting the command though.

Does anybody have an idea what is causing this "freezing"? It is messing up my home assistant configuration because it does not send the state through mqtt.

Thank you in advance!

**Comment by sidoh** [comment]
There were a couple of bugs that caused crashes that are fixed in the latest release.  So make sure you're running [1.8.5](https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.8.5) if you aren't already.

Otherwise...

Are you sure it's not just missing the packet?  Does it catch packets more reliably when the remote is closer to the nRF?  

If so, some suggestions:

1. Try reorienting the nRF.  I've found the antennae are slightly directional.
2. Try an nRF with [low-noise amplification](https://en.wikipedia.org/wiki/Low-noise_amplifier) like [this one](https://www.amazon.com/Longruner-Transceiver-Antistatic-Compatible-LKY67/dp/B06WLH4ZG6).  Make sure you have a really good power supply and a capacitor across Vin and Gnd on the nRF if you try this.  Also try to get a handful of the modules if you're buying new ones -- QA is really poor in my experience.
3. Try a different nRF.  [Knockoffs are really common, and have pretty poor QA](https://github.com/sidoh/esp8266_milight_hub/wiki/Troubleshooting#bad-radio-module).

If not, I'd still recommend #s (2) and (3).  But also worth checking Serial logs to see if there's anything fishy in there.

**Comment by sidoh** [comment]
Please let me know if you're still having issues and we can reopen.
