### ISSUE TITLE
Can i use the ibox1 lamp function?

### ISSUE THREAD

**Issue by danpowpow** [sidoh/esp8266_milight_hub#409]
I just picked up some spare bulbs and they came with the ibox hub - the one that looks like a little lamp. Is there a way to use the lamp without usingbthe hub functionality?
Sorry if ive missed the answer somewhere, i did have a scoot around but didnt find any info

**Comment by sidoh** [comment]
Hi Dan,

espMH doesn't help with that as the onboard lamp isn't controllable by the 2.4 GHz protocol.

You can, however, control it with the UDP API.  Not sure if that helps you.

Gonna close the issue because it's not something the project can help with, but happy to continue discussing over the ticket if you have further questions.
