### ISSUE TITLE
Is it possible to manually change the MAC address ?

### ISSUE THREAD

**Issue by Lstt2005** [sidoh/esp8266_milight_hub#46]
Is it possible to store different mac address in string with configuration in index.html with each udp server? (For BilIght android app)?

**Comment by sidoh** [comment]
Certainly possible. I'm a little hesitant to make things over-configurable, though. Don't want to make things unnecessarily confusing.

What do you think about responding with something like:

```
00:00:00:00:11:22
```

When `0x1122` is the device ID bound to the given port? Do you feel like that'd accomplish what you want?

**Comment by Lstt2005** [comment]
Yes, I think that would suit me. Thank you!

**Comment by Lstt2005** [comment]
And whether it is possible to track the variant, for example on port 5987, if a connection is established, then the next request from the application (MiLight)  is responsible for assigning a MAC address, for example ID + 1, to the next request from the ID + 2 application, etc., to try to deceive the application (Milight) (only on port 5987)?

**Comment by sidoh** [comment]
Yeah I guess that's possible, but it seems like that'd be super unreliable and confusing. What should happen if, for example, one session expires or disconnects?

**Comment by Lstt2005** [comment]
Yes, I agree (( .. I want to try to scan the application for requests and answers, it may be possible to find all the same semblance of the Id session ..

**Comment by sidoh** [comment]
Go for it! Would love it if you figured out a way to do it. :)

I just pushed a change to v1.2.0 that does this.

**Comment by Lstt2005** [comment]
>I just pushed a change to v1.2.0 that does this.
It's work with Bilight - https://github.com/JasperG/bilight (https://play.google.com/store/apps/details?id=com.jaspergoes.bilight) !

**Comment by sidoh** [comment]
sweet. :)

**Comment by sidoh** [comment]
Gonna close since it sounds like this worked, but feel free to re-open if I missed something.

**Comment by alexeinz** [comment]
I wonder if the change works, Openhab also requires a specific mac address for discovery and I cant seem to make it work
00000000B55D for example doesnt work

**Comment by sidoh** [comment]
Got it. I was a little worried about that. It seemed nicer to advertise meaningful information (i.e., the device ID) in the response rather than meaningless information (i.e., the ESP's hardware address), but certainly not at the expense of breaking stuff.

I suppose we could expose a setting. @Lstt2005, how useful is this feature to you? Would it break your workflow we responded with the hardware address instead of the device ID?

**Comment by alexeinz** [comment]
atleast for openhab, each gateway requires a separate mac address, there seem to be no other way to add the device in openhab ( unless using mqtt,but that would complicate things quite a bit )

**Comment by sidoh** [comment]
@alexeinz, do you happen to know what's causing OpenHAB to break? Asking because I'm concerned the issue is something else. I'd be a tiny bit surprised if OpenHAB was actually verifying the hardware address of the responding IP via ARP or something. It seems a little brittle.

**Comment by sidoh** [comment]
> atleast for openhab, each gateway requires a separate mac address, there seem to be no other way to add the device in openhab ( unless using mqtt,but that would complicate things quite a bit )

Do you have multiple gateways running with the same device ID?

**Comment by alexeinz** [comment]
no,the gateways all have separate device ID ( the device ID of the wifi boxes that the bulbs originally paired to ) 
Even though entered in Gateway servers, they are not discovered by openhab ( I do adjust the ports ) because openhab requires associated mac address,resolvable. See screenshot below.

It did manage to discover one gateway when I added the hardware mac address of the esp,but unreliably and that means i have to fully pair all bulbs to esp, which kind of defeats the purpose of the Gateway servers setting

![screen shot 2017-04-26 at 9 26 16 am](https://cloud.githubusercontent.com/assets/6789193/25413092/981582be-2a62-11e7-8a61-f1f760325250.png)

![screen shot 2017-04-26 at 9 30 28 am](https://cloud.githubusercontent.com/assets/6789193/25413184/475a750e-2a63-11e7-802c-9597928976fe.png)

**Comment by sidoh** [comment]
Ah, so it looks like this mechanism is optional. Does it not work if you just leave off the Bridge ID?

**Comment by alexeinz** [comment]
Well it is optional, but then it forces the bridge into v2 compatibility mode, and v6 devices will not function at all

**Comment by sidoh** [comment]
Sorry that I'm fumbling around a bit here. I've not used OpenHAB before.

That's unfortunate. Is it not possible to just add a gateway with an IP and a port, and tell OpenHAB that it's a v6 hub? That's basically how it works for HomeAssistant.

**Comment by alexeinz** [comment]
Yes, unfortunately this seems to be the functionality,
i think there is also open issue talking about same problem.
That said, this specific thread mentioned earlier creation of virtual mac addresses- tied into the virtual gateways... I had the impression this was implemented or you have decided against it in the end?

**Comment by sidoh** [comment]
To confirm - it's not possible to add a device without its version being set by the discovery mechanism?

It's worth noting that Milight's approach to discovery is extremely confused. The discovery protocol outlined in the [documentation](http://www.limitlessled.com/dev/) is actually only used by the official Milight app when configuring wifi settings on a new device, and is not implemented in esp8266_milight_hub. Under normal circumstances, the Milight app discovers new devices by broadcasting a few packets to port 8899, so I forwent implementing the "real" discovery mechanism.

It's certainly possible to implement the discovery protocol, and to reply with multiple arbitrary packets. Since I'm pretty fuzzy on how OpenHAB works, though, I could use some help in knowing what packets need to get sent.

Poking through OpenHAB's milight code, it looks like it's determining the version [here](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/protocol/MilightDiscover.java). Would it be sufficient to reply with multiple search results on port 48899, one for each UDP server?

For example, if you had an ESP with IP 10.0.0.100, and UDP servers on ports 800,801,802, bound to device IDs 0x1,0x2,0x3 respectively, do you think it'd be sufficient to reply with three packets as follows?

```
10.0.0.10,000000000001,HF-LPB100
```
```
10.0.0.10,000000000002,HF-LPB100
```
```
10.0.0.10,000000000003,HF-LPB100
```

**Comment by alexeinz** [comment]
Yes, it seems that this one here is the key to discover v3 and v6 
I am not sure what is the 3rd argument though.. would that be the host-id?

If you could make the change.. I can test it easily when I am back home in the evening.

            // Now loop forever, waiting to receive packets and printing them.
            while (!willbeclosed) {
                packet.setLength(buffer.length);
                datagramSocket.receive(packet);
                // **example: 10.1.1.27,ACCF23F57AD4,HF-LPB100**
                String[] msg = new String(buffer, 0, packet.getLength()).split(",");
                if (msg.length >= 2 && msg[1].length() == 12) {
                    // Stop resend timer if we got a packet.
                    if (resendTimer != null) {
                        resendTimer.cancel(true);
                        resendTimer = null;
                    }
                    // Determine version: Version 6 sends a third argument != ""
                    int version = msg.length >= 3 && msg[2].trim().length() > 0 ? 6 : 3;
                    // Notify all observers
                    discoverResult.bridgeDetected(((InetSocketAddress) packet.getSocketAddress()).getAddress(), msg[1],
                            version);
                } else {
                    logger.error("Unexpected data received {}", msg[0]);
                }

**Comment by sidoh** [comment]
According to the documentation, the third argument is just the string literal `HF-LPB100`. I guess maybe the old protocol doesn't include the third argument.

I'm happy to give it a go, but I'm a little worried that it's not going to work. See #71 for more detail.

**Comment by alexeinz** [comment]
yes , this should work , that string is the identifier
i believe here is complete info on what it expects to see to identify hub type
 https://github.com/home-assistant/home-assistant/issues/4676
