### ISSUE TITLE
Determine Offline/Online status of milight controller (in the hub dashboard)

### ISSUE THREAD

**Issue by ArshSoni** [sidoh/esp8266_milight_hub#798]
Trying to determine if the controller is ON or if the switch has been turned off and the device is offline? 

If the power to the bulb/controller has been turned off, HomeAssistant nor Milight-hub.local reflects this. 

When using WL5 controller, the miboxer app shows offline/online status

ESP: nodemcu, RGB-CCT

**Comment by sidoh** [comment]
I'm not aware of a way to know the status of a light device (controller or bulb). It's possible there have been some protocol updates since the last time I've gotten my hands dirty reverse engineering the RF but the only device-originated traffic I ever saw was from bulbs when certain effects were active (presumably to synchronize across many bulbs).
